name: Terraform docs and formatting
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.44.0
  docs:
    runs-on: ubuntu-22.04
    needs: formatting
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs and push changes back to PR branch
      uses: terraform-docs/gh-actions@d8f1a2272f04d6124103eb65815f007e091e756a
      with:
        working-dir: . 
        output-file: README.md
        output-method: inject
        output-format: markdown table
        indention: 3
        git-push: "true"