name: Terraform docs and formatting
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.42.0
  docs:
    runs-on: ubuntu-22.04
    needs: formatting
    steps:
    - uses: actions/checkout@v4.1.4
      with:
        ref: ${{ github.ref }}
    - name: Render terraform docs and push changes back to PR branch
      uses: terraform-docs/gh-actions@72ed18e5751c95dc36107dff832598081ff56eb9
      with:
        working-dir: . 
        output-file: README.md
        output-method: inject
        output-format: markdown table
        indention: 3
        git-push: "true"